# Exploration des données

In [77]:
# importations des packages nécessaires à l'analyse exploratoire des données
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [78]:
# Importation des données*
df = pd.read_csv (r"C:\Users\yacin\Desktop\Assurance projet\insurance_claims.csv", sep =",")

In [79]:
df.head(20)

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN
5,256,39,104594,2006-10-12,OH,250/500,1000,1351.10,0,478456,...,NO,64100,6410,6410,51280,Saab,95,2003,Y,NaN
6,137,34,413978,2000-06-04,IN,250/500,1000,1333.35,0,441716,...,?,78650,21450,7150,50050,Nissan,Pathfinder,2012,N,NaN
7,165,37,429027,1990-02-03,IL,100/300,1000,1137.03,0,603195,...,YES,51590,9380,9380,32830,Audi,A5,2015,N,NaN
8,27,33,485665,1997-02-05,IL,100/300,500,1442.99,0,601734,...,YES,27700,2770,2770,22160,Toyota,Camry,2012,N,NaN
9,212,42,636550,2011-07-25,IL,100/300,500,1315.68,0,600983,...,?,42300,4700,4700,32900,Saab,92x,1996,N,NaN
10,235,42,543610,2002-05-26,OH,100/300,500,1253.12,4000000,462283,...,?,87010,7910,15820,63280,Ford,F150,2002,N,NaN
11,447,61,214618,1999-05-29,OH,100/300,2000,1137.16,0,615561,...,YES,114920,17680,17680,79560,Audi,A3,2006,N,NaN
12,60,23,842643,1997-11-20,OH,500/1000,500,1215.36,3000000,432220,...,NO,56520,4710,9420,42390,Saab,95,2000,N,NaN
13,121,34,626808,2012-10-26,OH,100/300,1000,936.61,0,464652,...,NO,7280,1120,1120,5040,Toyota,Highlander,2010,N,NaN
14,180,38,644081,1998-12-28,OH,250/500,2000,1301.13,0,476685,...,YES,46200,4200,8400,33600,Dodge,Neon,2003,Y,NaN
15,473,58,892874,1992-10-19,IN,100/300,2000,1131.40,0,458733,...,NO,63120,10520,10520,42080,Accura,MDX,1999,Y,NaN
16,70,26,558938,2005-06-08,OH,500/1000,1000,1199.44,5000000,619884,...,YES,52110,5790,5790,40530,Nissan,Maxima,2012,N,NaN
17,140,31,275265,2004-11-15,IN,500/1000,500,708.64,6000000,470610,...,YES,77880,14160,7080,56640,Suburu,Legacy,2015,N,NaN
18,160,37,921202,2014-12-28,OH,500/1000,500,1374.22,0,472135,...,NO,72930,6630,13260,53040,Accura,TL,2015,N,NaN
19,196,39,143972,1992-08-02,IN,500/1000,2000,1475.73,0,477670,...,NO,60400,6040,6040,48320,Nissan,Pathfinder,2014,N,NaN

#### Consultation des données

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), object(21)
memory usage: 312.6+ KB

In [81]:
df.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported', '_c39'],
      dtype='object')

In [82]:
df["insured_sex"].unique()

array(['MALE', 'FEMALE'], dtype=object)

In [108]:
df["auto_model"].unique()

array(['92x', 'E400', 'RAM', 'Tahoe', 'RSX', '95', 'Pathfinder', 'A5',
       'Camry', 'F150', 'A3', 'Highlander', 'Neon', 'MDX', 'Maxima',
       'Legacy', 'TL', 'Impreza', 'Forrestor', 'Escape', 'Corolla',
       '3 Series', 'C300', 'Wrangler', 'M5', 'X5', 'Civic', 'Passat',
       'Silverado', 'CRV', '93', 'Accord', 'X6', 'Malibu', 'Fusion',
       'Jetta', 'ML350', 'Ultima', 'Grand Cherokee'], dtype=object)

In [109]:
df["auto_make"].unique()

array(['Saab', 'Mercedes', 'Dodge', 'Chevrolet', 'Accura', 'Nissan',
       'Audi', 'Toyota', 'Ford', 'Suburu', 'BMW', 'Jeep', 'Honda',
       'Volkswagen'], dtype=object)

In [107]:
np.sort(df["auto_year"].unique())

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015])

In [83]:
df["incident_type"].unique()

array(['Single Vehicle Collision', 'Vehicle Theft',
       'Multi-vehicle Collision', 'Parked Car'], dtype=object)

In [84]:
df["insured_hobbies"].unique()

array(['sleeping', 'reading', 'board-games', 'bungie-jumping',
       'base-jumping', 'golf', 'camping', 'dancing', 'skydiving',
       'movies', 'hiking', 'yachting', 'paintball', 'chess', 'kayaking',
       'polo', 'basketball', 'video-games', 'cross-fit', 'exercise'],
      dtype=object)

In [85]:
df["insured_education_level"].unique()

array(['MD', 'PhD', 'Associate', 'Masters', 'High School', 'College',
       'JD'], dtype=object)

In [86]:
df["incident_location"].unique()

array(['9935 4th Drive', '6608 MLK Hwy', '7121 Francis Lane',
       '6956 Maple Drive', '3041 3rd Ave', '8973 Washington St',
       '5846 Weaver Drive', '3525 3rd Hwy', '4872 Rock Ridge',
       '3066 Francis Ave', '1558 1st Ridge', '5971 5th Hwy',
       '6655 5th Drive', '6582 Elm Lane', '6851 3rd Drive',
       '9573 Weaver Ave', '5074 3rd St', '4546 Tree St',
       '3842 Solo Ridge', '8101 3rd Ridge', '5380 Pine St',
       '8957 Weaver Drive', '2526 Embaracadero Ave', '5667 4th Drive',
       '2502 Apache Hwy', '3418 Texas Lane', '2533 Elm St',
       '3790 Andromedia Hwy', '3220 Rock Drive', '2100 Francis Drive',
       '4687 5th Drive', '9038 2nd Lane', '6092 5th Ave',
       '8353 Britain Ridge', '3540 Maple St', '3104 Sky Drive',
       '4981 Weaver St', '6676 Tree Lane', '3930 Embaracadero St',
       '3422 Flute St', '4862 Lincoln Hwy', '5719 2nd Lane',
       '3221 Solo Ridge', '6660 MLK Drive', '1699 Oak Drive',
       '4234 Cherokee Lane', '7476 4th St', '8907 Tree Ave',
       '6619 Flute Ave', '6011 Britain St', '5104 Francis Drive',
       '2280 4th Ave', '2644 Elm Drive', '7466 MLK Ridge', '5821 2nd St',
       '6723 Best Drive', '4866 4th Hwy', '5418 Britain Ave',
       '4296 Pine Hwy', '2299 1st St', '6618 Cherokee Drive',
       '7459 Flute St', '3567 4th Drive', '2457 Washington Ave',
       '1269 Flute Drive', '1218 Sky Hwy', '9169 Pine Ridge',
       '8538 Texas Lane', '5783 Oak Ave', '7721 Washington Ridge',
       '8006 Maple Hwy', '6751 Pine Ridge', '2324 Texas Ridge',
       '7923 Elm Ave', '4755 Best Lane', '5053 Tree Drive',
       '2078 3rd Ave', '2804 Best St', '7877 Sky Lane', '6530 Weaver Ave',
       '3087 Oak Hwy', '7098 Lincoln Hwy', '5124 Maple St',
       '2333 Maple Lane', '1012 5th Lane', '7477 MLK Drive',
       '9489 3rd St', '2087 Apache Ave', '5540 Sky St', '7238 2nd St',
       '8442 Britain Hwy', '1331 Britain Hwy', '5260 Francis Drive',
       '1135 Solo Lane', '9737 Solo Hwy', '3289 Britain Drive',
       '6550 Andromedia St', '1679 2nd Hwy', '3998 Flute St',
       '2430 MLK Ave', '7717 Britain Hwy', '7773 Tree Hwy',
       '2199 Texas Drive', '1028 Sky Lane', '4154 Lincoln Hwy',
       '8085 Andromedia St', '4793 4th Ridge', '7428 Sky Hwy',
       '2306 5th Lane', '3052 Weaver Ridge', '5211 Weaver Drive',
       '7253 MLK St', '1454 5th Ridge', '5622 Best Ridge',
       '4574 Britain Hwy', '4539 Texas St', '8118 Elm Ridge',
       '3814 Britain Drive', '4614 MLK Ave', '1628 Best Drive',
       '8381 Solo Hwy', '2100 MLK St', '5071 Flute Ridge',
       '7551 Britain Lane', '2275 Best Lane', '1598 3rd Drive',
       '7740 MLK St', '1240 Tree Lane', '8983 Francis Ridge',
       '7756 Solo Drive', '9034 Weaver Ridge', '1126 Texas Hwy',
       '2808 Elm St', '5061 Francis Ave', '4965 MLK Drive',
       '8668 Flute St', '2577 Washington Drive', '7709 Rock Lane',
       '9358 Texas Ridge', '8080 Oak Lane', '6408 Weaver Ridge',
       '5532 Weaver Ridge', '9101 2nd Hwy', '8576 Andromedia St',
       '6315 2nd Lane', '1536 Flute Drive', '4672 MLK St',
       '2204 Washington Lane', '9484 Pine Drive', '5431 3rd Ridge',
       '7121 Britain Drive', '8586 1st Ridge', '7582 Pine Drive',
       '1388 Embaracadero Hwy', '5621 4th Ave', '8150 Washington Ridge',
       '4268 2nd Ave', '6375 2nd Lane', '3770 Flute Drive',
       '1562 Britain St', '1681 Cherokee Hwy', '7523 Oak Lane',
       '1815 Cherokee Drive', '9316 Pine Ave', '2733 Texas Drive',
       '7684 Francis Ridge', '8991 Embaracadero Ave', '4905 Francis Ave',
       '7783 Lincoln Hwy', '8749 Tree St', '4985 Sky Lane',
       '7534 MLK Hwy', '8689 Maple Hwy', '9153 3rd Hwy', '5904 1st Drive',
       '4519 Embaracadero St', '9706 MLK Lane', '6012 Texas Hwy',
       '4098 Weaver Ridge', '6193 1st Hwy', '4053 Sky Lane',
       '8964 Francis St', '9748 Sky Drive', '2293 Washington Ave',
       '3656 Solo Ave', '8579 Apache Drive', '2003 Maple Hwy',
       '5445 Tree Hwy', '9730 2nd Hwy', '7819 Oak St', '1845 Best St',
       '2500 Tree St', '6955 Pine Drive', '6165 Rock Ridge',
       '3653 Elm Drive', '5812 3rd Hwy', '4939 Best St', '4964 Elm Lane',
       '9588 Solo St', '8718 Apache Lane', '3590 Best Hwy',
       '6149 Best Ridge', '4116 Embaracadero Lane', '3486 Flute Ave',
       '5994 5th Ave', '9138 3rd St', '3743 Andromedia Ridge',
       '7644 Tree Ridge', '3167 2nd St', '3327 Lincoln Drive',
       '8621 Best Ridge', '3878 Tree Lane', '9760 Solo Lane',
       '9138 1st St', '3414 Elm Ave', '3172 Tree Ridge', '6104 Oak Ave',
       '9742 5th Ridge', '8782 3rd St', '9798 Sky Ridge',
       '5483 Francis Drive', '2005 Texas Hwy', '6634 Texas Ridge',
       '8655 Cherokee Lane', '4955 Lincoln Ridge', '7705 Best Ridge',
       '5838 Pine Lane', '7331 Sky Hwy', '5640 Embaracadero Lane',
       '9610 Cherokee St', '3550 Washington Ave', '5277 Texas Lane',
       '3654 Cherokee Ave', '7380 5th Hwy', '2539 Embaracadero Ridge',
       '4693 Lincoln Hwy', '2376 Sky Ridge', '1273 Rock Lane',
       '8281 Lincoln Lane', '6429 4th Hwy', '2201 4th Lane',
       '5506 Best St', '8404 Embaracadero St', '2117 Lincoln Hwy',
       '6359 MLK Ridge', '9751 Sky Ridge', '9020 Elm Ave', '1830 Sky St',
       '6067 Weaver Ridge', '1840 Embaracadero Ave', '4058 Tree Drive',
       '4983 MLK Ridge', '9744 Texas Drive', '8821 Elm St',
       '2886 Tree Ridge', '5236 Weaver Drive', '5862 Apache Ridge',
       '7859 4th Ridge', '6259 Weaver St', '9980 Lincoln Ave',
       '7828 Cherokee Ave', '5812 Oak St', '2318 Washington Hwy',
       '8809 Flute St', '3184 Oak Ave', '6493 Lincoln Lane',
       '7162 Maple Ave', '5455 Tree Ridge', '5778 Pine Ridge',
       '3797 Solo Lane', '9373 Pine Hwy', '1365 Francis Ave',
       '9239 Washington Ridge', '3416 Washington Drive', '1923 2nd Hwy',
       '6451 1st Hwy', '1267 Francis Hwy', '4158 Washington Lane',
       '3796 Cherokee Drive', '7434 Oak Hwy', '5178 Weaver Hwy',
       '8477 Francis Hwy', '7693 Britain Lane', '3658 Rock Drive',
       '2617 Andromedia Drive', '9279 Oak Hwy', '3439 Andromedia Hwy',
       '5901 Elm Drive', '3982 Washington Hwy', '3376 5th Drive',
       '3936 Tree Drive', '6605 Tree Ave', '3102 Apache St',
       '7756 Pine Hwy', '7142 5th Lane', '2914 Oak Drive',
       '6522 Apache Drive', '5279 Pine Ridge', '8078 Britain Hwy',
       '1133 Apache St', '2873 Flute Ave', '8509 Apache St',
       '8245 4th Hwy', '3094 Best Lane', '8188 Tree Ave', '5224 5th Lane',
       '2230 1st St', '6719 Flute St', '8064 4th Ave',
       '2469 Francis Lane', '4671 5th Ridge', '6985 Maple Lane',
       '7791 Britain Ridge', '6355 4th Hwy', '3495 Britain Drive',
       '2980 Sky Ridge', '5914 Oak Ave', '3835 5th Ave', '5925 Tree Hwy',
       '6250 1st Ridge', '1346 5th Lane', '1128 Maple Lane',
       '6309 Cherokee Ave', '4618 Flute Ave', '6191 Oak Lane',
       '1316 Britain Ridge', '5924 Maple Drive', '8917 Tree Ridge',
       '3966 Francis Ridge', '1507 Solo Ave', '4272 Oak Ridge',
       '4434 Lincoln Ave', '7529 Solo Ridge', '8096 Apache Hwy',
       '9417 Tree Hwy', '3809 Texas Lane', '1540 Apache Lane',
       '2337 Lincoln Hwy', '6770 1st St', '4119 Texas St',
       '4347 2nd Ridge', '1091 1st Drive', '8203 Lincoln Ave',
       '9154 MLK Hwy', '5780 4th Ave', '6945 Texas Hwy', '5639 1st Ridge',
       '3834 Pine St', '1358 Maple St', '7460 Apache Lane',
       '5771 Sky Ave', '2865 Maple Lane', '8940 Elm Ave', '1215 Pine Hwy',
       '6874 Maple Ridge', '8834 Elm Drive', '8542 Lincoln Ridge',
       '9397 Francis St', '4907 Andromedia Drive', '4429 Washington St',
       '2651 MLK Lane', '2942 1st Lane', '6317 Best St',
       '1555 Washington Lane', '1919 4th Lane', '5480 3rd Ridge',
       '8864 Tree Ridge', '2777 Solo Drive', '9929 Rock Drive',
       '4143 Maple Ridge', '7121 Rock St', '9067 Texas Ave',
       '9245 Weaver Ridge', '4585 Francis Ave', '6738 Francis Hwy',
       '7576 Pine Ridge', '9105 Tree Lane', '2299 Britain Drive',
       '1914 Francis St', '6658 Weaver St', '1985 5th Ave',
       '1707 Sky Ave', '6456 Andromedia Drive', '5649 Texas Ave',
       '1220 MLK Ave', '1589 Pine St', '8906 Elm Lane', '2654 Elm Drive',
       '6681 Texas Ridge', '7782 Rock St', '9286 Oak Ave', '8758 5th St',
       '7281 Maple Hwy', '7571 Elm Ridge', '6738 Washington Hwy',
       '4188 Britain Ave', '6934 Lincoln Ave', '6390 Apache St',
       '7615 Weaver Drive', '6409 Cherokee Drive', '1123 5th Lane',
       '5168 5th Ave', '3697 Apache Drive', '1910 Sky Ave',
       '8954 Apache Lane', '3110 Lincoln Lane', '6035 Rock Ave',
       '2220 1st Lane', '4972 Francis Lane', '6957 Weaver Drive',
       '1512 Rock Lane', '3693 Pine Ave', '9879 Apache Drive',
       '2494 Andromedia Drive', '4615 Embaracadero Ave',
       '1929 Britain Drive', '5051 Elm St', '9910 Maple Ave',
       '5602 Britain St', '6889 Cherokee St', '3926 Rock Lane',
       '6717 Best Drive', '6117 4th Ave', '2668 Cherokee St',
       '6838 Flute Lane', '6583 MLK Ridge', '6492 4th Lane',
       '7299 Apache St', '2756 Britain Hwy', '9360 3rd Drive',
       '1655 Francis Hwy', '9720 Lincoln Hwy', '7066 Texas Ave',
       '9728 Britain Hwy', '4486 Cherokee Ridge', '8021 Flute Ave',
       '2774 Apache Drive', '2787 MLK St', '9847 Elm St',
       '4629 Elm Ridge', '5585 Washington Drive', '3925 Sky St',
       '3903 Oak Ave', '3805 Lincoln Hwy', '4055 2nd Drive',
       '3707 Oak Ridge', '7327 Lincoln Drive', '9369 Flute Hwy',
       '4239 Weaver Ave', '6044 Weaver Drive', '8879 1st Drive',
       '9488 Best Drive', '7500 Texas Ridge', '2048 3rd Ridge',
       '3419 Apache St', '9875 MLK Ave', '3553 Texas Ave', '4335 1st St',
       '9070 Tree Ave', '3900 Texas St', '9657 5th Ave',
       '5765 Washington St', '5997 Embaracadero Drive', '1738 Solo Lane',
       '2903 Weaver Drive', '8926 Texas Ridge', '4231 3rd Ave',
       '8049 4th St', '6501 5th Drive', '7909 Andromedia Hwy',
       '5865 Sky Lane', '1957 Washington Ave', '7649 Texas St',
       '1992 Britain Drive', '9685 Sky Ridge', '3457 Texas Lane',
       '7693 Cherokee Lane', '3167 4th Ridge', '1617 Rock Drive',
       '7877 3rd Ridge', '9325 Lincoln Drive', '5855 Apache St',
       '1328 Texas Lane', '4567 Pine Ave', '7575 Pine St',
       '2850 Washington St', '9169 Cherokee Hwy', '6443 Washington Ridge',
       '6751 5th Hwy', '2289 Weaver Ridge', '8306 1st Drive',
       '2603 Andromedia Hwy', '6479 Francis Ave', '6428 Andromedia Lane',
       '9081 Cherokee Hwy', '1532 Washington St', '4625 MLK Drive',
       '1529 Elm Ridge', '2086 Francis Drive', '9066 Best Ridge',
       '7178 Best Drive', '9821 Francis Ave', '7061 Cherokee Drive',
       '1325 1st Lane', '3769 Sky St', '8489 Pine Hwy', '6329 Apache Ave',
       '9293 Pine Lane', '9224 Sky Drive', '8862 Maple Ridge',
       '3492 Flute Lane', '6484 Tree Drive', '4554 Sky Ave',
       '5201 Texas Hwy', '3982 Weaver Lane', '3660 Andromedia Hwy',
       '7135 Flute Lane', '4414 Solo Drive', '2920 5th Ave',
       '2986 MLK Drive', '1580 Maple Lane', '3706 Texas Hwy',
       '9109 Britain Drive', '2290 4th Ave', '4232 Britain Ridge',
       '6677 Andromedia Drive', '5868 Sky Hwy', '3053 Lincoln Drive',
       '7041 Tree Ridge', '7223 Embaracadero St', '8081 Flute Ridge',
       '8618 Texas Lane', '3508 Washington St', '2193 4th Ridge',
       '8897 Sky St', '9611 Pine Ridge', '7825 1st Ridge', '3039 Oak Hwy',
       '8204 Pine Lane', '9787 Andromedia Ave', '9633 Rock Hwy',
       '6303 1st Drive', '2014 Rock Ave', '8983 Tree St', '6260 5th Lane',
       '2725 Britain Ridge', '3089 Oak Ridge', '6206 3rd Ridge',
       '7240 5th Ridge', '8100 3rd Ave', '3282 4th Lane',
       '3227 Maple Ave', '4264 Lincoln Ridge', '2215 Best Ave',
       '5363 Weaver Lane', '2397 Cherokee Ave', '9794 Embaracadero St',
       '1810 Elm Hwy', '9603 Texas Lane', '5650 Sky Drive',
       '9633 MLK Lane', '4981 Flute Hwy', '9078 Francis Ridge',
       '1381 Francis Ave', '6435 Texas Ave', '1248 MLK Ridge',
       '3323 1st Lane', '6971 Best Ridge', '7488 Lincoln Lane',
       '9007 Francis Hwy', '1491 Francis Ridge', '3659 Oak Lane',
       '4176 Britain Hwy', '5189 Francis Drive', '6515 Oak Lane',
       '7168 Andromedia Ridge', '7954 Tree Ridge', '1956 Apache St',
       '9918 Andromedia Drive', '5499 Flute Ridge', '3311 2nd Drive',
       '7609 Rock St', '4652 Flute Drive', '6853 Sky Hwy',
       '7780 Flute Lane', '1687 3rd Lane', '6378 Britain Ave',
       '1306 Andromedia St', '3664 Francis Ridge', '5985 Lincoln Lane',
       '3706 4th Hwy', '6603 Francis Hwy', '7069 4th Hwy',
       '5093 Flute Lane', '5894 Flute Drive', '8459 Apache Ave',
       '7447 Lincoln Ridge', '1821 Andromedia Ridge', '6859 Flute Ridge',
       '4175 Elm Ridge', '5007 Oak St', '5790 Flute Ridge',
       '8704 Britain Lane', '7816 MLK Lane', '3618 Maple Lane',
       '7705 Lincoln Drive', '8602 Washington Ridge',
       '2832 Andromedia Lane', '9760 4th Hwy', '2509 Rock Drive',
       '2063 Weaver St', '3818 Texas Ridge', '3929 Elm Ave',
       '9911 Britain Lane', '3246 Britain Ridge', '2696 Cherokee Ridge',
       '5249 4th Ave', '4721 Cherokee Hwy', '8212 Flute Ridge',
       '3592 MLK Ridge', '6494 4th Ave', '6608 Apache Lane',
       '1553 Lincoln St', '7628 4th Lane', '3028 5th St', '8949 Rock Hwy',
       '9751 Tree St', '4702 Texas Drive', '2757 4th Hwy',
       '6678 Weaver Drive', '8667 Weaver Lane', '4931 Maple Drive',
       '3808 5th Ave', '1725 Solo Lane', '8097 Maple Lane',
       '3320 5th Hwy', '9573 2nd Ave', '8336 1st Ridge', '3998 4th Hwy',
       '3966 Oak Hwy', '7601 Andromedia Lane', '5160 2nd Hwy',
       '3288 Tree Lane', '5874 1st Hwy', '6467 Best Ave', '6309 5th Ave',
       '8212 Rock Ave', '4107 MLK Ridge', '4558 3rd Hwy',
       '1762 Maple Hwy', '5532 Francis Lane', '6158 Sky Ridge',
       '9214 Elm Ridge', '1833 Solo Ave', '1953 Sky Lane',
       '6834 1st Drive', '9562 4th Ridge', '4835 Britain Ridge',
       '8548 Cherokee Ridge', '2352 MLK Drive', '9734 2nd Ridge',
       '3122 Apache Drive', '9816 Britain St', '8214 Flute St',
       '6259 Lincoln Hwy', '4492 Andromedia Ave', '6179 3rd Ridge',
       '3799 Embaracadero Drive', '5071 1st Lane', '6574 4th Drive',
       '2711 Britain Ave', '4214 MLK Ridge', '7976 Britain Drive',
       '4995 Weaver Ridge', '1515 Embaracadero St', '2968 Andromedia Ave',
       '9236 2nd Hwy', '9639 Britain Ridge', '9422 Washington Ridge',
       '1213 4th Lane', '3872 5th Drive', '9397 5th Hwy', '8876 1st St',
       '3397 5th Ave', '3263 Pine Ridge', '8639 5th Hwy',
       '5743 4th Ridge', '3555 Francis Ridge', '4939 Oak Lane',
       '3100 Best St', '3029 5th Ave', '8941 Solo Ridge',
       '4447 Francis Hwy', '7701 Tree St', '4653 Pine St', '8742 4th St',
       '7316 Texas Ave', '2950 MLK Ave', '8233 Tree Drive',
       '4642 Rock Ridge', '7733 Britain Lane', '2753 Cherokee Ave',
       '3995 Lincoln Hwy', '4095 MLK St', '5782 Rock Drive',
       '2900 Sky Drive', '1515 Pine Lane', '4876 Washington Drive',
       '5779 2nd Lane', '6706 Francis Drive', '6384 5th Ridge',
       '3006 Lincoln Ridge', '5352 Lincoln Drive', '6110 Rock Ridge',
       '7797 Tree Ridge', '4910 1st Lane', '8766 Lincoln Lane',
       '6399 Oak Drive', '3127 Flute St', '8920 Best Ave',
       '7314 Tree Drive', '8872 Oak Ridge', '5022 1st St',
       '3423 Francis Ave', '9529 4th Drive', '1818 Tree St',
       '4431 Rock St', '4782 Sky Lane', '7112 Weaver Ave',
       '4020 Best Drive', '2037 5th Drive', '4699 Texas Ridge',
       '1832 Elm Hwy', '5226 Maple St', '3771 4th St', '8701 5th Lane',
       '7574 4th St', '1989 Solo Lane', '6331 MLK Ave', '8453 Elm St',
       '1422 Flute Ave', '5058 4th Lane', '3098 Oak Lane',
       '9103 MLK Lane', '8624 Francis Ave', '2905 Embaracadero Drive',
       '3443 Maple Ridge', '1618 Maple Hwy', '3751 Tree Hwy',
       '6848 Elm Hwy', '4237 4th St', '6581 Rock Ridge',
       '7236 Apache Lane', '3846 4th Hwy', '5028 Maple Ridge',
       '7426 Rock Drive', '5771 Best St', '9818 Cherokee Ave',
       '7819 2nd Ave', '1331 Elm Ridge', '9240 Britain Ave',
       '6668 Andromedia Ridge', '5276 2nd Lane', '2889 Weaver St',
       '1879 4th Lane', '5499 Elm Hwy', '8822 Sky St', '4254 Best Ridge',
       '5812 Weaver Ave', '7155 Apache Drive', '1376 Pine St',
       '3340 3rd Hwy', '3097 4th Drive', '1916 Elm St',
       '8917 Cherokee Lane', '8492 Weaver Hwy', '3753 Francis Lane',
       '4545 4th Ridge', '2272 Embaracadero Drive', '5341 5th Ave',
       '7745 Washington Ridge', '1275 4th Ridge', '4857 Weaver St',
       '8211 Sky Hwy', '8617 Best Ave', '9856 Apache St', '1951 Best Ave',
       '1824 5th Lane', '7393 Washington St', '1386 Britain St',
       '7928 Maple Ridge', '1546 Cherokee Ave', '2003 2nd Hwy',
       '9418 5th Hwy', '8770 1st Lane', '1087 Flute Drive',
       '2217 Tree Lane', '6741 Oak Ridge', '2123 MLK Ridge',
       '4390 4th Drive', '1437 3rd Lane', '1186 Rock St', '4394 Oak St',
       '8368 Cherokee Ave', '4905 Best Lane', '3618 Sky Ave',
       '5459 MLK Ave', '1371 Texas Lane', '2654 Embaracadero St',
       '2123 Texas Ave', '4538 Flute Hwy', '4434 Weaver St',
       '2798 1st Ave', '2809 Francis Lane', '7281 Oak St',
       '9878 Washington Ave', '2537 5th Ave', '8493 Apache Drive',
       '2878 Britain Hwy', '2862 Tree Ridge', '4453 Best Ave',
       '5191 4th St', '1364 Best St', '8946 2nd Drive', '3726 MLK Hwy',
       '2820 Britain St', '2646 MLK Drive', '6256 Elm St',
       '9724 Maple St', '7397 4th Drive', '3488 Flute Lane',
       '9082 3rd Lane', '1941 5th Ridge', '5333 MLK Lane', '4577 Sky Hwy',
       '4814 Lincoln Lane', '2381 1st Hwy', '6939 3rd Hwy',
       '5269 Flute Hwy', '7197 2nd Drive', '1741 Best Ridge',
       '9148 4th Hwy', '4279 Solo Drive', '9177 Texas Ave',
       '5969 Francis St', '9942 Tree Ave', '5474 Weaver Hwy',
       '1102 Apache Hwy', '9214 Texas Drive', '8991 Texas Hwy',
       '9580 MLK Ave', '5868 Best Drive', '5318 5th Ave',
       '7502 Rock Lane', '4627 Elm Ridge', '5584 Britain Lane',
       '7002 Oak Hwy', '4780 Best Drive', '8995 1st Ave', '5586 2nd St',
       '1589 Best Ave', '1880 Weaver Drive', '7295 Tree Hwy',
       '8832 Pine Drive', '1620 Oak Ave', '3847 Elm Hwy',
       '3177 MLK Ridge', '3929 Oak Drive', '1469 Lincoln Drive',
       '9719 4th Lane', '3196 Cherokee St', '8492 Andromedia Ridge',
       '1353 Washington St', '6731 Andromedia Hwy', '5769 Texas Lane',
       '2849 Pine Drive', '2577 Texas Ridge', '3841 Washington Lane',
       '8125 Texas Ridge', '4826 5th St', '1578 5th Lane',
       '6440 Rock Lane', '5806 Embaracadero St', '1472 4th Drive',
       '5839 Weaver Lane', '7630 Rock Drive', '7144 Andromedia St',
       '9988 Rock Ridge', '7544 Washington Ave', '7201 Washington Ave',
       '8805 Cherokee Drive', '3275 Pine St', '7785 Lincoln Lane',
       '4994 Lincoln Drive', '1298 Maple Hwy', '2644 MLK Drive',
       '5630 1st Drive', '6137 MLK St', '5383 Maple Drive',
       '4460 4th Lane', '8524 Pine Lane', '8456 1st Ave',
       '3639 Flute Hwy', '7900 Sky Hwy', '7835 Cherokee Hwy',
       '1030 Pine Lane', '9278 Francis Ridge', '6604 Apache Drive',
       '2311 4th St', '9523 Solo Hwy', '3171 Andromedia Lane',
       '2492 Lincoln Lane', '4477 5th Ave', '6724 Andromedia St',
       '7495 Washington Ave', '4291 Sky Hwy', '5650 Rock Ave',
       '6888 Elm Ridge', '2352 Sky Drive', '5280 Pine Ave',
       '6638 Tree Drive', '5678 Lincoln Drive', '4496 Pine Lane',
       '8845 5th Ave', '9317 Apache Ave', '8638 3rd Ave',
       '3061 Francis Hwy', '1173 Andromedia Ave', '6068 2nd St',
       '7937 Weaver Ridge', '2823 Weaver Lane', '1809 Sky St',
       '9352 Washington Ave', '2697 Oak Drive', '1110 4th Drive',
       '7535 5th Lane', '9043 Maple Hwy', '3777 Maple Ave',
       '5608 Solo St', '6981 Weaver St', '4369 Maple Lane', '6931 Elm St',
       '7583 Washington Ave', '7552 3rd St', '1654 Pine St',
       '6058 Andromedia Hwy', '6536 MLK Hwy', '8198 Embaracadero Lane',
       '3447 Solo Ave', '1806 Weaver Ridge', '7930 Texas Ave',

In [87]:
df["insured_relationship"].unique() # à vérifier !

array(['husband', 'other-relative', 'own-child', 'unmarried', 'wife',
       'not-in-family'], dtype=object)

In [88]:
df["collision_type"].unique() # les types d'accidents
# remarque d'un point d'intérogation qu'on peut mettre et remplacer par 'other' ou 'Unknown'

array(['Side Collision', '?', 'Rear Collision', 'Front Collision'],
      dtype=object)

In [89]:
df["collision_type"] = df["collision_type"].replace("?", "unknown")

In [90]:
df["collision_type"].unique()

array(['Side Collision', 'unknown', 'Rear Collision', 'Front Collision'],
      dtype=object)

In [91]:
df["authorities_contacted"].unique() # remarque de nan qu'on vas remplacer par unconnu

array(['Police', nan, 'Fire', 'Other', 'Ambulance'], dtype=object)

In [92]:
df["authorities_contacted"] = df["authorities_contacted"].replace(np.nan, "unknown")

In [93]:
df["authorities_contacted"].unique()

array(['Police', 'unknown', 'Fire', 'Other', 'Ambulance'], dtype=object)

In [94]:
df["policy_state"].unique()

array(['OH', 'IN', 'IL'], dtype=object)

In [95]:
df["incident_severity"].unique()

array(['Major Damage', 'Minor Damage', 'Total Loss', 'Trivial Damage'],
      dtype=object)

In [96]:
df.describe()

,months_as_customer,age,policy_number,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,capital-gains,capital-loss,incident_hour_of_the_day,number_of_vehicles_involved,bodily_injuries,witnesses,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_year,_c39
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,0.0
mean,203.954000,38.948000,546238.648000,1136.000000,1256.406150,1.101000e+06,501214.488000,25126.100000,-26793.700000,11.644000,1.83900,0.992000,1.487000,52761.94000,7433.420000,7399.570000,37928.950000,2005.103000,NaN
std,115.113174,9.140287,257063.005276,611.864673,244.167395,2.297407e+06,71701.610941,27872.187708,28104.096686,6.951373,1.01888,0.820127,1.111335,26401.53319,4880.951853,4824.726179,18886.252893,6.015861,NaN
min,0.000000,19.000000,100804.000000,500.000000,433.330000,-1.000000e+06,430104.000000,0.000000,-111100.000000,0.000000,1.00000,0.000000,0.000000,100.00000,0.000000,0.000000,70.000000,1995.000000,NaN
25%,115.750000,32.000000,335980.250000,500.000000,1089.607500,0.000000e+00,448404.500000,0.000000,-51500.000000,6.000000,1.00000,0.000000,1.000000,41812.50000,4295.000000,4445.000000,30292.500000,2000.000000,NaN
50%,199.500000,38.000000,533135.000000,1000.000000,1257.200000,0.000000e+00,466445.500000,0.000000,-23250.000000,12.000000,1.00000,1.000000,1.000000,58055.00000,6775.000000,6750.000000,42100.000000,2005.000000,NaN
75%,276.250000,44.000000,759099.750000,2000.000000,1415.695000,0.000000e+00,603251.000000,51025.000000,0.000000,17.000000,3.00000,2.000000,2.000000,70592.50000,11305.000000,10885.000000,50822.500000,2010.000000,NaN
max,479.000000,64.000000,999435.000000,2000.000000,2047.590000,1.000000e+07,620962.000000,100500.000000,0.000000,23.000000,4.00000,2.000000,3.000000,114920.00000,21450.000000,23670.000000,79560.000000,2015.000000,NaN

#### Traitement de type de variables

In [ ]:
df[["incident_date", "policy_bind_date"]] = df[["incident_date", "policy_bind_date"]].apply(pd.to_datetime)